### ISSUE TITLE
Decide on the configuration language for `cardano-shell`

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-shell#1]
We want to decide on the language to use for configuration of `cardano-shell`.
Options include:
- Dhall
- A subset of Haskell (via GHC API?)
- JSON/YAML (via Aeson)

After a discussion with @ksaric, we appeared to have converged on the following list of properties we care about:
1. Configuration consistency checking (both off-line and runtime)
1. Danger of configuration doing Turing-complete things & even having side effects
1. Separation of schema from config
1. Minimum bureaucracy (as in Dhall forcing you to overspecify types & making sums cumbersome; or Haskell forcing you to have imports) (edited)
1. Implementation complexity (how do you implement configs as runtime-loadable Haskell values?)
1. Composability
1. Extensibility

**Comment by ksaric** [comment]
After a chat with @rvl I have got very useful information regarding the configuration and in what ways can the configuration story be simplified.
I would like to invite all @input-output-hk/devops to write down what they think should be changed with regards to the configuration. From what format to use to the most common problems, which pieces of configuration are critical and those that are not, any additional piece of information shapes the new project more to something useful and easy to use.

**Comment by ksaric** [comment]
From the chat I had with @rvl I can summarize the following:
- the launcher is somewhat complex and could be simplified
- part of that effort is the `node-ipc` work, which simplified some of the complexities of `launcher`
- the most difficult part of the system is the update system and the synchronization between the `node` and Daedalus is something which makes this more complex than it could be
- `dhall` is simpler in cases where the config is simple (I agree with that)
- the current `dhall` config in Daedalus is transformed during build time (of the installers) to the launcher configuration format (YAML).
