### ISSUE TITLE
E8.1 Launcher update system impl.

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-shell#132]
Launcher update system impl.

issues #131  #130 

@cleverca22 demonstrated how to build the windows installer using cross-compilation:

```
nix-build default.nix -A windows-installer --option builders ''
```
(ref: https://github.com/input-output-hk/daedalus/blob/develop/default.nix#L154)

and, the Linux installer:

```
nix-build release.nix -A mainnet-installer
````

**Comment by cleverca22** [comment]
`nix-build release.nix -A mainnet.installer` will build a linux installer for mainnet
