### ISSUE TITLE
Review configuration documentation

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#151]
We have primary configuration documentation which should be reviewed by the DevOps and QA team to see if we are on the same page.

**Comment by ksaric** [comment]
Found here - https://github.com/input-output-hk/cardano-shell/blob/develop/configuration.md

**Comment by ksaric** [comment]
There are two pieces of the configuration:
- constants - https://github.com/input-output-hk/cardano-shell/blob/develop/src/Cardano/Shell/Constants/Types.hs
- dhall configuration - https://github.com/input-output-hk/cardano-shell/blob/develop/src/Cardano/Shell/Configuration/Types.hs

Constants are written in Haskell, Dhall configuration is the configuration format.

The example for Dhall can be found here - https://github.com/input-output-hk/cardano-shell/tree/develop/dhall

**Comment by CodiePP** [comment]
this issue did not get enough attention and start to rot.
