### ISSUE TITLE
Add functionality for visualizing the node interactions on `shell`

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#164]
We can add simple and more understandable representation of what's going on in the `node-shell` and in the other parts of the system by adding a small set of functions to the current `cardano-shell` library functions.
They would be responsible for providing visualization of the "inner workings" of the node, displaying all the modules and how they interact, using which functions and which arguments.

**Comment by ksaric** [comment]
The `iohk-monitoring` is using http://hackage.haskell.org/package/threepenny-gui

**Comment by CodiePP** [comment]
I think this issue needs an initial design such that it becomes clear what the outcome should look like. An artefact of such an analysis could be a "mock" version of the visualisation as it would appear in a browser.

**Comment by ksaric** [comment]
The primary task is to capture the function calls and output them somewhere.
We can do that by creating a new layer and outputting the calls _somewhere_. It doesn't have to be a `threepenny-gui` or anything else.

This task was created as an idea, with the comments inside mostly for myself, so it might not be clear nor obvious what this task is all about, but the first phase is just using a simple "proxy" for the layer where we can capture data and notify something.

**Comment by ksaric** [comment]
For example, when we call `llLogDebug` we want to output to a file (that's the simplest for now) a call `llLogDebug 15` where `a`, the second parameter is the param type of `Show` and we can output to a file directly.
The new line could be a new call from a different function and so on...

**Comment by CodiePP** [comment]
> For example, when we call `llLogDebug` (
> 
> https://github.com/input-output-hk/cardano-shell/blob/d2ab3fdc2ad69d6b2b9ab8897010ee731a14b403/app/Cardano/Shell/Features/Logging.hs#L69
> ) we want to output to a file (that's the simplest for now) a call `llLogDebug 15` where "15" is `a`, the second parameter is the param type of `Show` and we can output to a file directly.
> The new line could be a new call from a different function and so on...

I think this is related to issue #211. Please, move it there.

**Comment by ksaric** [comment]
> > For example, when we call `llLogDebug` (
> > https://github.com/input-output-hk/cardano-shell/blob/d2ab3fdc2ad69d6b2b9ab8897010ee731a14b403/app/Cardano/Shell/Features/Logging.hs#L69
> > 
> > ) we want to output to a file (that's the simplest for now) a call `llLogDebug 15` where "15" is `a`, the second parameter is the param type of `Show` and we can output to a file directly.
> > The new line could be a new call from a different function and so on...
> 
> I think this is related to issue #211. Please, move it there.

It's not, it's part of this issue, a simple output to a file for each of the functions. 
That is the first step.

**Comment by HirotoShioi** [comment]
I'll try to draw something to see if I understand this issue correctly.

**Comment by HirotoShioi** [comment]
![D1](https://user-images.githubusercontent.com/15665039/60856819-7458dc80-a243-11e9-895e-6d3d0c4d46d8.jpg)

**Comment by HirotoShioi** [comment]
![Screenshot from 2019-07-09 12-18-12](https://user-images.githubusercontent.com/15665039/60856889-a9fdc580-a243-11e9-81aa-c82847c12755.png)

**Comment by HirotoShioi** [comment]
![Screenshot from 2019-07-09 14-14-05](https://user-images.githubusercontent.com/15665039/60861030-dcafba00-a253-11e9-9386-343194bc4a4b.png)

**Comment by CodiePP** [comment]
very nice! Thanks @HirotoShioi
