### ISSUE TITLE
Move the exception handling from node-ipc to use ExceptT

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#183]
After some of the comments from @erikd, I concluded that what he proposed made a lot of sense and it would be a nice idea to have all the modules use the common exception handling "scheme" - https://github.com/input-output-hk/cardano-shell/pull/153#discussion_r285487166

So we should switch to `ExceptT`.

**Comment by erikd** [comment]
@ksaric Maybe just run this past other members of the broader `cardano-sl` team.

**Comment by CodiePP** [comment]
merged
