### ISSUE TITLE
Fix the closing pipe issue in node-ipc

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#189]
https://github.com/input-output-hk/cardano-shell/pull/185#issuecomment-502595402

Adding a union for both exceptions and include them in the tests.
While we are accepting non-determinism, we are also covering our tests completely.

**Comment by CodiePP** [comment]
this is in contrast to what the wallet BE uses NodeIPC: terminate when pipe closes.
(exception thrown? when?)

**Comment by ksaric** [comment]
Terminate what when the pipe closes? That sounds like "exit the program when an exception occurs".
Is that true for all pipe closes?
