### ISSUE TITLE
Configuration machinery integration

### ISSUE THREAD

**Issue by deepfire** [input-output-hk/cardano-shell#210]
# Context

Users of the configuration API would benefit from having a single source of truth for configurable values.  The status quo in `cardano-shell` has three different configuration mechanisms which are not seemingly integrated with each other, at least in context of `cardano-node`:

1. CLI (see https://github.com/input-output-hk/cardano-node/blob/master/app/Main.hs#L119)
2. Dhall config files (no mention in `cardano-node`)
3. Presets (`CardanoConfiguration` in https://github.com/input-output-hk/cardano-shell/blob/master/src/Cardano/Shell/Presets.hs#L145)

**Note**: *this is a prerequisite for* https://github.com/input-output-hk/cardano-node/issues/30.

# Requirements

1. Configuration API users should have a single, unified, final source of truth for configuration values, that is informed by the aforementioned mechanisms.
2. Maintenance of the separation between relative "constants" and "configurables". Sometimes the distinction is hard to make.
   - Here _constants_ are defined as environment/cluster defaults that are not necessarily available to CLI-based overriding.
3. No hard coded values: there should be no need to recompile `cardano-node` to override any values, even those that are classified as "constants". This does not mean that all values need to be necessarily configurable via CLI -- any runtime configuration specification method is acceptable.

# Open questions

1. There is no overarching type for the overall configuration.  Do we want one?  To what degree do we think we want/can keep configuration isolated per feature?  How do we approach ambiguities?
2. What is the authoritative definition for the notion of "constants"?  Are they indeed just a combination of two properties:
    a. Having environment (mainnet/testnet/staging/dev) -dependent defaults.
    b. Not having CLI representation.

    Do we, perhaps, want to separate these two properties and apply them to each option independently?

# Ideas

1. Towards the goal of a unified model of configuration, we could assemble a single registry of all configuration options.  That could help with:
   - avoiding duplication
   - finding the best place for new options
   - keeping track of the properties of the options -- users, environment dependency, CLI-overridability
   - maintaining an overall picture
   - setting up a point of collaboration in this area
  One could imagine this registry being kept as a spreadsheet -- since that would allow sorting on arbitrary columns, so as to allow easy queries.

2. Towards the requirement №2, we could externalise the hard-coded values for the `CardanoConfiguration` values into a external file -- and a Dhall file, for that matter, so as to reuse an existing mechanism.

3. Towards abstracted, generalised merging of options layers (presets, Dhall, CLI), we could consider the _Generalised Options Monoid_ approach by Fischoff: https://medium.com/@jonathangfischoff/the-partial-options-monoid-pattern-31914a71fc67

**Comment by ksaric** [comment]
@deepfire The idea is ok - have a common configuration structure and have the ability to override _some params_.
But, as we talked, it is not the case that we have the same structure for everything (CLI, Dhall config, constants) since there are things that exist only in one of them.
The problem is that there are some params, like the `k` param, which will probably remain constant for most of the cases - `mainnet` and `testnet` users will benefit from having a simple constant instead of passing it in via CLI, and we don't want to burden all users with knowing what `k` is.

So, it would be best to actually see which params you need, you can write them down here as we talked and we can go from there. 
Doing smart things before we see an actual example might be leading us to some path that might not turn out to be useful in the end. And it might turn out that this way of structuring the configuration like we tried to do with `cardano-shell` is not the best way.

Let's see what you (and others) need and let us conclude what's best in that case.

**Comment by Jimbo4350** [comment]
Also note `Genesis.Config` is piped here: https://github.com/input-output-hk/cardano-node/blob/master/app/CLI.hs#L72

@deepfire  I like the look of the Generalised Options Monoid approach.

**Comment by deepfire** [comment]
> But, as we talked, it is not the case that we have the same structure for everything (CLI, Dhall config, constants) since there are things that exist only in one of them.
> ...
> The problem is that there are some params, like the k param, which will probably remain constant for most of the cases - mainnet and testnet users will benefit from having a simple constant instead of passing it in via CLI, and we don't want to burden all users with knowing what k is.

@ksaric, I completely agree on lack of necessity to have all parameters represented in CLI -- and that is reflected in the issue already, I believe.  Now the question of constants vs. Dhall -- why don't we simply move constants to Dhall files? That way we get just two different sources (constants and CLI).

> Let's see what you (and others) need and let us conclude what's best in that case.

I completely agree -- and I think that getting an overall picture of our parameters is the way forward -- so that allows us to make any conclusions.  The idea №1 seems to be an important first step.  I'm ready to start on this, as I said -- all I'd want is some consensus on its necessity, and that it's not just voices in my head : -)

> @deepfire I like the look of the Generalised Options Monoid approach. Maybe we can combine Dhall with this? We can hide parameters like k from the user by using default values (i.e defaultPartialOptions in the medium article)

@Jimbo4350, yes, I'd love to explore this approach, actually.

**Comment by ksaric** [comment]
@deepfire Do you know which params you need? Can you write them down here?

**Comment by deepfire** [comment]
@ksaric, my particular need is to be able to choose a genesis config from the CLI.

**Comment by disassembler** [comment]
My thoughts based on what I've seen in SL and in rust code:

* Protocol constants like `k`, `protocolMagic` and `networkMagic` I think should only be in the genesis config. I don't see a need to reflect this in a config file outside of genesis, unless I'm missing some need to have it duplicated.

* "pre-baked" genesis files used for config so I can specify `--cluster=mainnet`, `--cluster=testnet` or `--cluster=staging`.

* Ability to specify a custom genesis if I'm not using a pre-baked genesis with `--cluster=custom --genesis-config=benchmark1.json`.

* The actual config outside of genesis should be as limited as possible. Ideally it would specify protocol version and some pre-seeded relay addresses only on a core/relay node and on a wallet would have additional configuration information like TLS and port information (if https enabled, or sock file to use if using unix sockets) and daedalus configuration would have all of the above mentioned attributes plus update server URL and application version.

**Comment by deepfire** [comment]
> "pre-baked" genesis files used for config so I can specify --cluster=mainnet, --cluster=testnet or --cluster=staging.

@disassembler, the current way the genesis file is specified is via a `FilePath`+Hash tuple. So we could make these `--cluster=X` names reference presets of those tuples, then (in addition to whatever else is appropriate).
