### ISSUE TITLE
Fixing nested configuration problems

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#235]
I encountered an issue in a PR after checking the comments from @deepfire - https://github.com/input-output-hk/cardano-shell/pull/232#pullrequestreview-265450795

It turns out that there is an issue when you want to override nested configuration from CLI.
For example, when you have a structure like this:
```
data FullConfiguration = FullConfiguration
    { version   :: !Int
    , subConfig :: !(Last SubConfiguration)
    } deriving (Eq, Show, Semigroup, Monoid)

data SubConfiguration = SubConfiguration
    { name      :: !(Last Text)
    , age       :: !(Last Int)
    } deriving (Eq, Show, Semigroup, Monoid)
```
If you override the field `name` then the field `age` is overridden with the value `Nothing` since the top level `SubConfiguration` overrides **both fields**.

Some people suggested the use of `mempty` here - https://github.com/input-output-hk/cardano-node/pull/60#discussion_r307697007 which is nice but it's also kind of tricky for me since I can't easily reason about the code anymore but have to write it down and go through it.

A simpler way is to flatten the configuration to have only a single level and then it all works correctly!

**Comment by dcoutts** [comment]
Concretely, my suggestion is this:
```diff
- subConfig :: !(Last SubConfiguration)
+ subConfig :: !SubConfiguration
```

All the monoid derivation still works fine, because `SubConfiguration` is a monoid (a product of monoids). But now the monoid operation "descends" into the nested structure!

**Comment by ksaric** [comment]
Additional example found here - https://github.com/haskell/cabal/blob/master/cabal-install/Distribution/Client/ProjectConfig/Types.hs

Switching to the pattern from @dcoutts using monoidal structures.
