### ISSUE TITLE
T8.2.2 Manual test package

### ISSUE THREAD

**Issue by CodiePP** [input-output-hk/cardano-shell#249]
the package should contain the launcher and a mock of the wallet FE which returns the desired exit codes
the package should be implemented in such a way that it can be tested/run on the platforms Windows, MacOSX, Linux
the package will be run manually, but could also be reused by unit tests (#128)

**Comment by HirotoShioi** [comment]
For this, I need help from DevOps. I've tried testing on Windows by compiling this code and failed miserably

**Comment by HirotoShioi** [comment]
https://github.com/input-output-hk/cardano-shell/tree/master/cardano-launcher#manual-testing-on-windows
