### ISSUE TITLE
Add the lock file and the support for the lock file.

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#339]
We can currently run the launcher several times and have several instances running.
We need to add the lock file and the support for running a single instance **_ONLY_**.

**Comment by ksaric** [comment]
We currently have the `lockfile` - https://github.com/input-output-hk/cardano-shell/blob/master/lockfile
We just need the support from the installer to include it in the installation.

@cleverca22 ?

**Comment by ksaric** [comment]
We will just create the `lockfile` and get a lock on it, instead of packing it with the installation.

**Comment by cleverca22** [comment]
the lock file should be in the state directory

with the current implementation, its impossible to open 2 clusters at once
