### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by HirotoShioi** [input-output-hk/cardano-shell#346]
After yesterday's discussion, we decided that we should add these sections to the wiki page.

- [x] How error handling is being done on each platform
- [x] Environment variable that launcher requires
- [x] How the launcher exits (About exit code)
- [x] On update section, briefly note that this process was decided on the assumption that the user's computer was not compromised.
- [x] Logging
- [x] Testing

**Comment by CodiePP** [comment]
let's review this beginning next week.

**Comment by HirotoShioi** [comment]
- Error handling [Link](https://github.com/input-output-hk/cardano-shell/wiki/Launcher#error-handling)
- Environment variable that launcher requires [Link](https://github.com/input-output-hk/cardano-shell/wiki/Launcher#requirements)
-  How the launcher exits (About exit code) [Link](https://github.com/input-output-hk/cardano-shell/wiki/Launcher#shutting-down-the-launcher)
- Logging [Link](https://github.com/input-output-hk/cardano-shell/wiki/Launcher#logging)
-  Testing [Link](https://github.com/input-output-hk/cardano-shell/wiki/Launcher#testing)

**Comment by CodiePP** [comment]
very good. thank you.
