### ISSUE TITLE
Message.hs:Use explicit function instead of typeclass foo

### ISSUE THREAD

**Issue by Heinrich-CH** [input-output-hk/cardano-shell#364]
Hello,
When trying to build this with newer upstream libraries (```cabal``` with ```--allow-newer``` flag), I get the following error:
```
src/Cardano/Shell/NodeIPC/Message.hs:35:65: error:
    • No instance for (ConvertText BSLC.ByteString GHC.Base.String)
        arising from a use of ‘toS’
    • In the second argument of ‘(<>)’, namely ‘toS blob’
      In the expression: "Failed to decode given blob: " <> toS blob
      In an equation for ‘P.show’:
          P.show (DecodeFail blob)
            = "Failed to decode given blob: " <> toS blob
   |
35 |     show (DecodeFail blob) = "Failed to decode given blob: " <> toS blob
   |                                                                 ^^^^^^^^
```
A fix for a similar error was suggested in Cardano-Prelude by @erikd (see [link](https://github.com/input-output-hk/cardano-prelude/pull/112/commits/c95b22775b6e0cef13829bd861a7b736c414e2fb)).
However, the exact same fix doesn't apply.

**Comment by erikd** [comment]
@Heinrich-CH The only reason you are seeing this error is because you are using the `--allow-newer` cabal flag.

**Comment by Heinrich-CH** [comment]
Fixed (and compiled the rest of the code) by downgrading [protolude ](https://hackage.haskell.org/package/protolude) from 0.3.0 to 0.2.4.
Leaving this bug open in case there are plans to upgrade the protolude dependency or add an explicit constraint.

**Comment by erikd** [comment]
Stop using the `--allow-newer` flag and this problem disappears.

Using `--allow-newer` is a user error.
