### ISSUE TITLE
Ensure that the node shuts within a reasonable amount of time

### ISSUE THREAD

**Issue by ksaric** [input-output-hk/cardano-shell#59]
Ensure that the node shuts within a reasonable amount of time, after receiving a shutdown signal (ExitFailure 20, the signal that the wallet has properly shut down).

After the issues regarding a very long delay shutting the node down found in the previous version, which can be found here https://iohk.myjetbrains.com/youtrack/issue/DEVOPS-1234, the idea is to write down a test that ensures that the shutdown operation completes rather soon, so the database doesn't get corrupted or a myriad of other things properly terminate.

The new test would be to initiate a node shutdown and check that it does terminate within a "reasonable" amount of time, e.g. a couple of seconds.

**Comment by CodiePP** [comment]
is there such a test?
